server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: students
          uri: http://student-service:8091
          predicates:
            - Path=/api/v1/students/**

        - id: parents
          uri: http://parent-service:8093
          predicates:
            - Path=/api/v1/parents/**

        - id: parents
          uri: http://parent-service:8093
          predicates:
            - Path=/api/v1/family/**

        - id: activite
          uri: http://activitykids-service:8086
          predicates:
            - Path=/api/v1/activity/**

        - id: activite
          uri: http://activitykids-service:8086
          predicates:
            - Path=/api/v1/activity/class/**

        - id: activite
          uri: http://activitykids-service:8086
          predicates:
            - Path=/api/v1/calendar/**

        - id: payment
          uri: http://payment-service:8094
          predicates:
            - Path=/api/v1/payment/**

        - id: dalyReport
          uri: http://dailyreport-service:8088
          predicates:
            - Path=/api/v1/daly/**

        - id: dalyReport
          uri: http://dailyreport-service:8088
          predicates:
            - Path=/api/v1/evaluation/**

        - id: teachers
          uri: http://teacher-service:8092
          predicates:
            - Path=/api/v1/teachers/**

        - id: events
          uri: http://events-service:8095
          predicates:
            - Path=/api/v1/event/**

        - id: events
          uri: http://events-service:8095
          predicates:
            - Path=/api/v1/parentActivity/**

        - id: token
          uri: http://security-service:8081
          predicates:
            - Path=/api/v1/auth/register/**

        - id: token
          uri: http://security-service:8081
          predicates:
            - Path=/api/v1/auth/authenticate/**

        - id: token
          uri: http://security-service:8081
          predicates:
            - Path=/api/v1/auth/forgot-password/**

        - id: token
          uri: http://security-service:8081
          predicates:
            - Path=/api/v1/auth/set-password/**

        - id: storage
          uri: http://storage-service:5001
          predicates:
            - Path=/api/v1/storage/files/**

        - id: storage
          uri: http://storage-service:5001
          predicates:
            - Path=/api/v1/storage/document-files/**

        - id: chatdb
          uri: http://chat-service:8090
          predicates:
            - Path=/api/v1/messages/**

        - id: chatdb
          uri: http://chat-service:8090
          predicates:
            - Path=/api/v1/chatRooms/**

        - id: chatdb
          uri: http://chat-service:8099
          predicates:
            - Path=/**

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
