eureka:
  instance:
    hostname: student-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka

server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/students
    username: school     # Assurez-vous d'utiliser le bon nom d'utilisateur
    password: root        # Le mot de passe doit correspondre à ce qui est défini dans docker-compose
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
