eureka:
  instance:
    hostname: subject-service
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka

server:
  port: 8096
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/subject
    hikari:
      username: postgres
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
